### ISSUE TITLE
The Bug Report Issue Template is not very fun

### ISSUE THREAD

**Issue by rbaiyasi** [kevmuri/intersect-training-day2-nonforked#3]
**Describe the bug**
I feel like it could really be jazzed up a lot.

**To Reproduce**
1. Make a new bug report issue.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by garymotz** [comment]
It's plenty fun.
